name: 'compile'
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
  pull-requests: read
  pages: write
  id-token: write
  checks: write
jobs:
  compile:
    name: Generate cards.pdf
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: cards.tex
        latexmk_use_xelatex: true
        pre_compile: "export max_print_line=1000"
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: result
        path: cards.pdf
    - name: Show cards.log
      run: cat cards.log
    - name: Archive compile logs
      uses: actions/upload-artifact@v3
      with:
        name: compile-log
        path: cards.log
  gh-pages:
    name: Generate website
    uses: ./.github/workflows/gh-pages.yml
    needs: compile
  checks:
    uses: ./.github/workflows/latex-compile-check.yml
    needs: compile