name: 'latex-compile-check'
on:
  workflow_dispatch:
  workflow_run:
    workflows: [compile]
    types: [completed]
permissions:
  contents: read
  pull-requests: read
  pages: write
  id-token: write
  checks: write
jobs:
  create-check:
    runs-on: ubuntu-latest
    steps:
      - name: Show context
        uses: actions/github-script@v6
        with:
          script: console.log(JSON.stringify(context, null, 2))